### ISSUE TITLE
Add URL validation

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#1147]
Add validation of the unsafe URLs, such as that can be received from the global scope (`CONFIG`).

**Comment by ashklianko** [comment]
After investigating and checking through our code:

1. The one place where user input is used as url is LinkModalDialog and url is being validated there
2. All user input is already sanitized 
3. In other places "unsafe" urls like the ones from CONFIG vars are not a threat to UI, but a potential problem only for a backend when malformed url is used in a request
4. There are no libs good enough that sanitize urls only, the reason is that there are hundrefs of potential attack vectors https://owasp.org/www-community/xss-filter-evasion-cheatsheet and they are to be handled in general in html, as we do with DOMPurify now

**Comment by ashklianko** [comment]
@alansemenov and @edloidas do you see any other potential problems with urls?

**Comment by alansemenov** [comment]
Valid input, closing this
