### ISSUE TITLE
Add PUBLISH_FIRST to supported query fields

### ISSUE THREAD

**Issue by edloidas** [enonic/lib-admin-ui#454]
@alansemenov commented on [Wed Apr 18 2018](https://github.com/enonic/app-contentstudio/issues/17)

Add options "Published - Ascending" and "Published - Descending". Sort by `publish.from`

![image](https://user-images.githubusercontent.com/11612490/38925000-ae4ca69c-42fe-11e8-99eb-76a41055465a.png)

**Comment by sigdestad** [comment]
I guess we should use publish.first - not publish.from?
Any thoughts on this?

**Comment by sigdestad** [comment]
There is a pot problem here, what the user sees in the UI before and after publishing will change :-/

**Comment by alansemenov** [comment]
I think publish.first has little meaning when it comes to sorting - it never changes. If you change/publish items often and sort by Publish then you would want to see those that were published recently on top.

**Comment by sigdestad** [comment]
Uhmm.. What was the conclusion here?

**Comment by alansemenov** [comment]
I tested now and it's true that we don't update `publish.from`... but why? I think it's a bug. It's ok that `publish.from=publish.first` on the very first publish, but what is the point in keeping the same value in `publish.from` after I published it for the second time a month later? 

What's important when it comes to sorting I think, is that if I already have my content sorted by "Published descending" and then I publish a modified content item somewhere in the middle of the list then it moves directly on top after being published.

**Comment by sigdestad** [comment]
It is definetly not a bug, publish.from is used for "scheduling" the publish. When we get support for scheduling modifications, we may use this to set publish.from for that specific version too.

**Comment by sigdestad** [comment]
Lets just make sure that we sort on publish.first when this property is set.. But maybe it should actually specify: publish.first DESC, modified.DESC or something like that - so in admin last modified will be on top, unless it is actually published?

**Comment by alansemenov** [comment]
@sigdestad This is more complicated than planned. As of now - and that's a default behaviour - hits with a missing field will be placed last when sorted by that field.

In order to have not-yet-published items on top we'll have to implement server-side changes to ElasticSearch integration which will affect a lot of different codebase (node layer, libs, services etc.). 

So we have two options:
1) Have not-yet-published items listed at the bottom (this will still separate them from published items, so it will still help)
2) Create backend tasks to implement this and postpone this to the next release (it's too risky to make these changes now that we're approaching feature freeze on 6.15)

**Comment by sigdestad** [comment]
I see.. I guess we have to start with this basic approach then!
