### ISSUE TITLE
Error when applying changes when editing fragments

### ISSUE THREAD

**Issue by RF0** [enonic/lib-admin-ui#757]
Tested in 6.15.1-SNAPSHOT, Chrome

0. Make sure vhost is enabled (see comment below)
1. Install app-superhero-blog from market
2. Edit the front page
3. Right click any part f.x. "Recent Posts" and choose "Save as fragment"
4. Choose "Edit fragment"
5. Click the part in live edit and change a configuration f.x. Title and click apply
6. Changes are not applied. Spinner hangs. Observe the browser Console log and see attached stacktrace (stacktrace is from building with -Penv=dev mode)

[setAttribute-stacktrace.txt](https://github.com/enonic/lib-admin-ui/files/2297218/setAttribute-stacktrace.txt)

**Comment by RF0** [comment]
I have done some testing on different machines, and I have reproduced it on mac and windows. This problem actually only appears when vhost is enabled on the server. F.x. if i enter the following in the com.enonic.xp.web.vhost.cfg file, the problem gets back, but disappears when i set enabled = false. Is this expected behavior?

enabled = true

mapping.test.host = localhost
mapping.test.source = /
mapping.test.target = /
mapping.test.userStore = system

**Comment by alansemenov** [comment]
@GlennRicaud This looks like a server-side issue. 
Basically, after changes are applied to a component (f.ex. a part) inside the Inspect panel, we make an ajax request to component url (f.ex. ``/admin/portal/edit/draft/1a9d8cc8-9896-4cda-aa1d-3a2f761360dc/_/component``) to fetch its html source and render only the changed component in LiveEdit. The problem is that when vhost is enabled, the component url returns HTML source of the entire page instead of only the component's. 

Please investigate.
